extends: default
rules:
  line-length:
    max: 120
  document-start: disable
  truthy:
    allowed-values: ["true", "false", "on"]  # "on:" is how GitHub Actions starts triggers
  comments:
    min-spaces-from-content: 1
